cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    mango:
      age: 25
      failed_login_attempts: 0
      gender: "\uC5EC\uC131"
      logged_in: false
      nickname: mangowoman
      password: $2b$12$HnNwaKZgHgq.muzUN/heGukK3aYlb61Pu9SBYQgvCcFBRdBcwzsVm
    mangoman:
      age: 30
      failed_login_attempts: 0
      gender: "\uB0A8\uC131"
      logged_in: false
      nickname: Man
      password: $2b$12$NSLS/UFLSf3W5KwsFqgsSO5Dvo5g3lNEyJsTb9AQkjsfKE/asYKrG
